name: swizzle_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  curved_navigation_bar: ^1.0.6 
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.17  
  cloud_firestore: ^5.6.1
  uuid: ^4.2.2
  shared_preferences: ^2.3.5
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  file_picker: ^8.3.1
  http: ^1.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - lib/assets/logo.png
  fonts:
    - family: NovaCut
      fonts:
        - asset: lib/assets/fonts/NovaCut-Regular.ttf
        
